<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()):?>
<?php $helper = $this->helper('Spiff\Personalize\Helper\Data'); ?>
<?php $currencyCode = $helper->getCurrentCurrencyCode(); ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()):?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       min="0"
                       value="<?= $block->getProductDefaultQty() * 1 ?>"
                       title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
            </div>
        </div>
        <?php endif; ?>
        <?php if ($_product->getEnableSpiff() == '1'): ?>
            <div class="actions add-to-cart">
                <button type="button" class="action primary tocart" id="spiff-button">
                    <span><?= /* @escapeNotVerified */ __('PERSONALIZE NOW') ?></span>
                </button>
            </div>
        <?php else: ?>
            <div class="actions">
                <button type="submit"
                        title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                        class="action primary tocart"
                        id="product-addtocart-button" disabled>
                    <span><?= $block->escapeHtml($buttonTitle) ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        <?php endif ?>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>

<?php if ($_product->getEnableSpiff() == '1'): ?>
    <script type="text/javascript" async src="https://assets.spiff.com.au/api.js"></script>
    <script>
        require(['axios', 'Magento_Customer/js/customer-data'], (axios, customerData) => {
            const spiffButton = document.querySelector('#spiff-button')
            const sku = `<?= $_product->getSku() ?>`
            spiffButton.addEventListener('click', function() {
                const product = new window.Spiff.IntegrationProduct('<?= $_product->getSpiffIntegrationProductId() ?>');
                product.on('ready', () => {
                   
                    const hostedExperienceOptions = {
                        presentmentCurrency: '<?= $currencyCode ?>',
                        product: product,
                    };

                    const hostedExperience = new window.Spiff.HostedExperience(hostedExperienceOptions);
                    hostedExperience.on("complete", async (result) => {
                        // Handle the result of the workflow experience..
                        // request to get quote id
                        try {
                            const { data: syncData } = await axios.post('/rest/V1/customer-sync')

                            const customerToken = syncData.customer_token;
                            const cartId = syncData.cart_id;

                            const sections = ['cart'];
                            customerData.invalidate(sections);
                            customerData.reload(sections, true);

                            if (customerToken) {
                                const options = {
                                    headers: {
                                        'Content-Type': 'application/json',
                                        'Authorization': `Bearer ${customerToken}`
                                    }
                                }
                                const { data: quoteId } = await axios.post('/rest/V1/carts/mine', {}, options)
                                const payload = {
                                    cartItem: {
                                        sku,
                                        quote_id: quoteId,
                                        qty: 1
                                    },
                                    customItemInformation: {
                                        'custom_price': (result.baseCost + result.optionsCost) / 100,
                                        'transaction_id': result.transactionId
                                    }
                                }
                                await axios.post('/rest/V1/carts/mine/custom-items', payload, options)
                                await axios.post('/rest/V1/carts/mine/update-custom-items', payload, options)
                            } else {
                                const payload = {
                                    cartItem: {
                                        sku,
                                        quote_id: cartId,
                                        qty: 1
                                    },
                                    customItemInformation: {
                                        'custom_price': (result.baseCost + result.optionsCost) / 100,
                                        'transaction_id': result.transactionId
                                    }
                                }
                                await axios.post(`/rest/V1/guest-carts/${cartId}/custom-items`, payload)
                                await axios.post(`/rest/V1/guest-carts/${cartId}/update-custom-items`, payload)
                            }
                             window.location.href = '/checkout/cart'
                        } catch(e) {
                            console.log(e)
                        }
                    });
                    hostedExperience.execute();
                });
                product.confirmActive();
            });
        })
    </script>
<?php endif ?>