
<?php /** @var \Magento\Sales\Block\Adminhtml\Order\View\Items\Renderer\DefaultRenderer $block */ ?>
<?php $_item = $block->getItem() ?>
<?php $block->setPriceDataObject($_item) ?>
<tr>
    <?php $i = 0;
    $columns = $block->getColumns();
    $lastItemNumber = count($columns) ?>
  
    <?php foreach ($columns as $columnName => $columnClass):?>
        <?php $i++; ?>
        <td class="<?= /* @noEscape */ $columnClass ?><?= /* @noEscape */ ($i === $lastItemNumber ? ' last' : '') ?>">
           <?= /* @escapeNotVerified */ $block->getColumnHtml($_item, $columnName) ?>
        </td>
    <?php endforeach; ?>
    <td class="product-image">
        <?php $product =  $_item->getProduct();?>
        <?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();?>
 
        <?php  $imagewidth=100;
        $imageheight=100;
        $imageHelper  = $objectManager->get('\Magento\Catalog\Helper\Image');
        $image_url = $imageHelper->init($product, 'small_image')->setImageFile($product->getSmallImage())->resize($imagewidth, $imageheight)->getUrl();
        ?>
        <img src="<?= $image_url;?>" />
    </td>
    <?php if ($_item->getSpiffTransactionId()): ?>
                    <tr class="spiff-id">
                        <td colspan="5"><?= __('Spiff Transaction Id') . ": " . $_item->getSpiffTransactionId() ?></td>
                    </tr>
    <?php endif; ?>
</tr>

